### ISSUE TITLE
Problem with Z axis orientation

### ISSUE THREAD

**Issue by edenexposito** [Valkaari/c4D_PyGoZ#2]
Hello Again,

Other problem seems be related with Z axis. 

Tools exported from zBrush to C4D through GoZ seems be orientated to -Z instead +Z axis.

Would be great a branch with this fix!

**Comment by Valkaari** [comment]
i don't see any issue here but issue is moved [to this one](https://github.com/Valkaari/c4D_PyGoZ/issues/3)
