### ISSUE TITLE
Coffee files fixed with Scale and Axis Z orientation

### ISSUE THREAD

**Issue by edenexposito** [Valkaari/c4D_PyGoZ#3]
Hello, 

I've fixed GoZ coffee files to solve both issues.

Here you can download it: https://www.dropbox.com/s/8838pnw84kdamf6/GoZ_scaleFix.zip?dl=0

It would be great if you port these fix to python too. 

Thanks

**Comment by Valkaari** [comment]
hello, 

First, thanks for the feedback, i really appreciate.

The "problem" here is that i translated the script created by Pixologic as it is. The scale factor are coming from their script. I'll keep that issue opened to see if other people are complaining about the scale.


about the Z axis : 
I don't have any issue here, the object pointing to Z axis in zbrush is pointing to Z axis in cinema4D and what i sculpt in X side is on  X side on Cinema4D. 

Did I missed your modification in your fix for that part ? 


Cheers
Manuel

**Comment by edenexposito** [comment]
Thanks for your response.

Try to adjust a tool with zPlugin "Scale Master" and then translate it to C4D through GoZ.

Check scale result and Z axis orientation in C4D. With default GoZ from Pixologic scale seems be *1000 times bigger and object Z is reversed. To check it, try to export same tool from "Scale Master" directly and check booth.

With my fix, result exported by Scale Master and GoZ are the same.

Thanks!

**Comment by Valkaari** [comment]
I do agree, but if you are not using ScaleMaster that will create really tiny object in cinema4D. (if  you do nothing).

I've created a new Branch for ScaleMaster Users. Thanks for the fix and your time.
